### PR TITLE
2536 create safe copy

### LINKED ISSUE #2536: Create safe copy updates
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#1432ee9c5bc280bbb014cbfc61f5d954

### PR DESCRIPTION
**Pull request by DarksightKellar**
closes #2536

## Screenshot

Screenshot 2024-11-20 at 21 01 09

Snuck in this update, hover state for made with love copy
regular:
Screenshot 2024-11-20 at 21 28 28
hover:
Screenshot 2024-11-20 at 21 27 09

### CODE REVIEW

**Review by adamgall — APPROVED** [review]

**Review by mudrila — APPROVED** [review]

**Comment by parkermccurley** [comment]
“NFT Voting Safe” => “ERC-721 Token Voting”
“Assign voting rights and ownership privileges to ERC-721 token holders” => “Best for adding governance capabilities to an NFT collection.”

**Comment by parkermccurley** [comment]
Can the “Made with Love” hover effect be a filled in, semitransparent highlight like the effect on Audit and version number? Or is the outline the only option?

**Comment by DarksightKellar** [comment]
> Can the “Made with Love” hover effect be a filled in, semitransparent highlight like the effect on Audit and version number? Or is the outline the only option?

Gonna rope in design for this to determine what color combo will make sense for a fill highlight
@decentdao/design

**Comment by DarksightKellar** [comment]
Thanks @xanaramoss !

**Pull request merged**
