### PR TITLE
Proper active payments count `EVERYWHERE`

### LINKED ISSUE #2293: Active payments not showing on desktop
- As the title says, active payment is not showing on desktop.
- The little green counter does show up but it shows `0`
- Safe is here: sep:0x5ecB0Cb2002Db1EF86D92DcA9963839982cDEe15
- I created Safe, role, and added payment on mobile (iOS, Safari, Coinbase Wallet)
- Desktop is mac OS, Arc browser

Image
Image

### PR DESCRIPTION
**Pull request by mudrila**
Add missing filtering of active payments for showing proper payments count

Closes #2293

### CODE REVIEW

**Review by DarksightKellar — APPROVED** [review]

**Review by adamgall — APPROVED** [review]

**Review by nicolaus-sherrill — DISMISSED** [review]
Screenshot 2024-08-23 at 10 42 24 AM
I am still seeing this same role show up without an active payment on desktop, despite there being an active stream.

**Review by Da-Colon — APPROVED** [review]

**Comment by nicolaus-sherrill** [comment]
recording


<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/details?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD&hatId=0xaac26be5e48b1859b982553e0ed9da801827d128cddd7f96627e8cdcb60eba2f
Browser:   Chrome 127.0.0.0 on Mac OS 10.15.7
Viewport:  1425 x 904 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2309.app.dev.decentdao.org%2Froles%2Fedit%2Fdetails%3Fdao%3Dsep%3A0xe20221A8939F9373C091262CBEF9493aca196acD%26hatId%3D0xaac26be5e48b1859b982553e0ed9da801827d128cddd7f96627e8cdcb60eba2f&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=127.0&resolution=1425x904&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2309.app.dev.decentdao.org/roles/edit/details?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD&hatId=0xaac26be5e48b1859b982553e0ed9da801827d128cddd7f96627e8cdcb60eba2f) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=66ccb3f9866789000868b25e&commentID=66cdf6f4d7595335f5a369cc&resolution=resolved)

**Comment by xraystyle1980** [comment]
screenshot

Trying to add a payment stream to these roles but am getting "unable to encode proposal data"
<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/summary?dao=sep:0x11b9F3f68154C8E55A6b42a3f709807badA4E1Ef
Browser:   Chrome 128.0.0.0 on Mac OS 10.15.7
Viewport:  1708 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2309.app.dev.decentdao.org%2Froles%2Fedit%2Fsummary%3Fdao%3Dsep%3A0x11b9F3f68154C8E55A6b42a3f709807badA4E1Ef&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=128.0&resolution=1708x1027&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2309.app.dev.decentdao.org/roles/edit/summary?dao=sep:0x11b9F3f68154C8E55A6b42a3f709807badA4E1Ef) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=66ccb3f9866789000868b25e&commentID=66ce5e62401f1cab52b7aa5b&resolution=resolved)

**Comment by Da-Colon** [comment]
> screenshot
> 
> Trying to add a payment stream to these roles but am getting "unable to encode proposal data"
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-2309.app.dev.decentdao.org/roles/edit/summary?dao=sep:0x11b9F3f68154C8E55A6b42a3f709807badA4E1Ef) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=66ccb3f9866789000868b25e&commentID=66ce5e62401f1cab52b7aa5b&resolution=resolved)

This should be addressed in the #2283 branch.

**Pull request merged**
