### PR TITLE
`[PRD]` | New homepage

### PR DESCRIPTION
**Pull request by adamgall**
Closes https://github.com/decentdao/decent-interface/issues/2586
Closes https://github.com/decentdao/decent-interface/issues/2589

### CODE REVIEW

**Comment by nicolaus-sherrill** [comment]
These icons should both be sized at 24px. Arrows are currently 20px.
Screenshot 2024-12-03 at 2 12 27 PM

**Comment by adamgall** [comment]
> These icons should both be sized at 24px. Arrows are currently 20px. Screenshot 2024-12-03 at 2 12 27 PM

Ah yes another good callout. Fixed and pushed.

**Comment by nicolaus-sherrill** [comment]
Ah, sorry, small design revision request for this button type, too. Can you adjust both lines of text in these buttons to adopt the `labels.large` text style with 0 spacing between them?

 Screenshot 2024-12-03 at 2 26 49 PM
 
Oversight on my part using the heading sizes in buttons (rushing design 🤪). We should stick with button sized text in all of our button types, unless there is a specific expressive/brand storytelling reason to go bigger.

**Comment by adamgall** [comment]
> Ah, sorry, small design revision request for this button type, too. Can you adjust both lines of text in these buttons to adopt the `labels.large` text style with 0 spacing between them?
> 
> Screenshot 2024-12-03 at 2 26 49 PM
> Oversight on my part using the heading sizes in buttons (rushing design 🤪). We should stick with button sized text in all of our button types, unless there is a specific expressive/brand storytelling reason to go bigger.

Just pushed a fix for this

**Comment by nicolaus-sherrill** [comment]
@adamgall okay _last_ design QA thing I've noticed on this page. That first header needs to be bumped down to align with the bottom of the search bar input. On mobile when those elements stack, we should be seeing the same spacing between the header & My DAOs list as with the Getting Started and new cards, which I believe is 16px.
Screenshot 2024-12-03 at 2 44 09 PM

Everything else looks locked tf in

**Comment by adamgall** [comment]
> @adamgall okay _last_ design QA thing I've noticed on this page. That first header needs to be bumped down to align with the bottom of the search bar input. On mobile when those elements stack, we should be seeing the same spacing between the header & My DAOs list as with the Getting Started and new cards, which I believe is 16px. Screenshot 2024-12-03 at 2 44 09 PM
> 
> Everything else looks locked tf in

OK just pushed a fix for this.

**Review by DarksightKellar — APPROVED** [review]
🤌🏾🤌🏾🤌🏾

**Review by Da-Colon — APPROVED** [review]

**Comment by DarksightKellar** [comment]
The big green button... It calls to me...

**Pull request merged**
