### PR TITLE
`1533` Toggling Safes on Organization page

### LINKED ISSUE #1533: Can't Favorite Multiple DAOs on hierarchy page
On the Hierarchy page, 

If you have multiple DAOs. if you click through to add multiple ones at the time, only one is actually saved to local storage, as on a refresh these won't update correctly leaving only one change saved (maybe two sometimes)

### PR DESCRIPTION
**Pull request by Da-Colon**
Fixes #1533

Go to Safe with multiple sub Safes. Then toggle favorites and navigate away and back (or refresh) should now save all changes properly

### CODE REVIEW

**Comment by tomstuart123** [comment]
@Da-Colon can you check the video I just [sent here](https://decentdao.slack.com/archives/C06QZTUTKRC/p1716548806433229?thread_ts=1716548771.976629&cid=C06QZTUTKRC) - 

I went through your flow and its still not 100%

**Comment by adamgall** [comment]
@tomstuart123 your video demonstrates a different issue. This PR addresses the issue where you were unable to favorite/unfavorite Safes consistently from a Safe's hierarchy page.

**Comment by tomstuart123** [comment]
are I misunderstood the test flow above and what @Da-Colon meant by 'toggle'. Let me retry

**Comment by adamgall** [comment]
@tomstuart123 no worries, @Da-Colon probably should have used the words "Hierarchy page" somewhere in this PR!

**Comment by tomstuart123** [comment]
Right after doing the test flow correctly both in production and on this PR, I understand it now. It all worked well in the new PR so will approve

**Review by tomstuart123 — APPROVED** [review]

**Comment by tomstuart123** [comment]
Approved.

Re; my seperate issue in the video above, I was sadly able to replicate this issue also in the PR 1909 (the fix for 1515 issue)

Recommend we create a new issue for this.

**Review by adamgall — COMMENTED** [review]
`isConnectedFavorited` is never used, please remove it

**Comment by adamgall** [comment]
> Recommend we create a new issue for this.

@tomstuart123 please do!

**Review by adamgall — COMMENTED** [review]
@Da-Colon is the `useEffect` in here really doing anything useful?

can we remove it and instantiate the state via:

```ts
const [favoritesList, setFavoritesList] = useState<string[]>(getValue(CacheKeys.FAVORITES));
```

**Review by adamgall — COMMENTED** [review]
@Da-Colon I also question whether the `toggleFavorite` needs to be wrapped in a `useCallback`.

**Review by adamgall — APPROVED** [review]
@Da-Colon However I will say that the changes you made _within_ the `toggleFavorite` function look good and, logically following the changes, make sense 👍 .

Giving an approval here, but would appreciate your take on if the following full implementation of `useFavorites.ts` is acceptable/appropriate:

```ts
import { useState } from 'react';
import { getAddress } from 'viem';
import { CacheKeys, CacheExpiry } from '../../utils/cache/cacheDefaults';
import { useLocalStorage } from '../../utils/cache/useLocalStorage';

export const useAccountFavorites = () => {
  const { setValue, getValue } = useLocalStorage();
  const [favoritesList, setFavoritesList] = useState<string[]>(getValue(CacheKeys.FAVORITES));

  const toggleFavorite = (address: string) => {
    const normalizedAddress = getAddress(address);
    const favorites: string[] = getValue(CacheKeys.FAVORITES);
    let updatedFavorites: string[] = [];

    if (favorites.includes(normalizedAddress)) {
      updatedFavorites = favorites.filter(favorite => favorite !== normalizedAddress);
    } else {
      updatedFavorites = favorites.concat([normalizedAddress]);
    }

    setValue(CacheKeys.FAVORITES, updatedFavorites, CacheExpiry.NEVER);
    setFavoritesList(updatedFavorites);
  };

  return { favoritesList, toggleFavorite };
};
```

**Comment by Da-Colon** [comment]
@tomstuart123 sorry was trying to retrain my brain on new copy ha.

**Pull request merged**
