### PR TITLE
`Root` / Remove Typechain

### PR DESCRIPTION
**Pull request by adamgall**
This is the root branch where all efforts to fully remove TypeChain from the codebase will be gathered.

## Testing Instructions

> The intention of this PR's "manual testing" is to touch every place in the app where data is read from, or written to, the blockchain, and ensuring that all goes as expected.

If you're reading this...

- Please dig into some of the "Testing flows" below. As you run across code that might not be covered by any one of these existing flows, **please add more testing flow paths into the tree to capture the spirit our stated intention!**
- As you run across bugs that you believe were caused by this PR, please fix and commit as you see fit.
- As you run across bugs that you believe existed on `develop` already, please open an issue in our project board.

### Testing flows

- [x] Create Safe ✅
  - [x] Multisig ([tx](https://sepolia.etherscan.io/tx/0x1dabbe5c3b527d5f09d9db6c8cb501833209ac90660c653fac0d581d0fb2256e), [dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x4382B09ad177adf4F57dF8c4E17B4c2900890906))
  - [x] ERC20 ✅
    - [x] New Token ([tx](https://sepolia.etherscan.io/tx/0xa00b8e57c5be0007c2e66ff5055c033d9c50c4bb3185bd02453caa33261751ba), [dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x1172393d4c91f0bBce02e799b806C3005Ad0fBE4))
    - [x] Wrap existing Token ✅
      - [x] Is already IVotes ([tx](https://sepolia.etherscan.io/tx/0x5787ca31d75b73d3f122bdca85016bbd11b9704c20e90930bbf70e30977d5de9), [dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0xEC9c809acB980781a0cB38915f3427AA77dD7fa1))
      - [x] Is not already IVotes ([tx](https://sepolia.etherscan.io/tx/0x47e4ce9952b20ab3780a60cb705c32a46f221eeabd24d372fa209f1626d58f62), [dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x9dDCc0A99774BD6Fb5573ac0b0DD1A3343405520))
  - [x] ERC721 ✅
    - [x] Single NFT ([tx](https://sepolia.etherscan.io/tx/0xbfb678cb78ad13d4bb459da63f203bec24c048d1ada63aaad00b2ceb3eef123b),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x64f9Bf4643Ec12eeAF7c8Af4C9b7354E94Cb22c1))
    - [x] Multiple NFTs ([tx](https://sepolia.etherscan.io/tx/0x736c44bbd4b8d8ee8356d8ea52357f5be5d052cb1e8829462170410317012ad7),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x934CbDA0CBeCb08A4Ab56dd48c504823C3da85b0))
- [x] Delegate voting tokens ✅
  - [x] Azorius ✅
    - [x] Tokens ([tx](https://sepolia.etherscan.io/tx/0x35e456a5629add4d5b77dc03bb8c8fd2906d204ba0b341acd868ca35f69367c8), [dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x871918DF39faF58934e6E50e81c064C1a243aF18))
    - [x] NFTs (not a thing)
- [x] Create proposal ✅
  - [x] Azorius ✅
    - [x] Tokens ([tx](https://sepolia.etherscan.io/tx/0x40e20ab974549894a56624f6e20e4d64ef0043611570c6710921d0b9fea5a2fb), [dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x871918DF39faF58934e6E50e81c064C1a243aF18))
    - [x] NFTs ([tx](https://sepolia.etherscan.io/tx/0x309160c6a445cdc9590ece202180e55d27cbc748ef37650712348e2b13befe78),[proposal](https://deploy-preview-1677.app.dev.decentdao.org/proposals/0?dao=sep:0xC555B5fFC8cEe091904e40d119C80e2334717b0e))
  - [x] Multisig ([tx](https://sepolia.etherscan.io/tx/0x1f61e192e8d205d834a02c3388d4aaa6a30c3efb70117a4a5b96622427d213ec), [dash](https://deploy-preview-1677.app.dev.decentdao.org/proposals/0xbd8070ff70021b5b4bf253fd7fcfc615b160d8facb6a65a42c69c4509acaf29b?dao=sep:0x4db2a8619a0643B2F280D8DBf96097319A42ba5a))
- [x] Vote on proposal ✅
  - [x] Azorius ✅
    - [x] Tokens ([tx](https://sepolia.etherscan.io/tx/0x5d2bc7306cc1cb26a3ae332dd50f157e94f18b8fc2846b5761d6c0134ea622a8),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x40fdB1FbcBCBA7F9dAaCF9C7386Ef57A0b0aE119))
    - [x] NFTs ✅
      - [x] Plain vote (vote once) ([tx](https://sepolia.etherscan.io/tx/0xfea5e56ab6fd75680e5edff0ed06093a304be323efff20531581f181e07ad76b),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0xC555B5fFC8cEe091904e40d119C80e2334717b0e))
      - [x] Vote multiple times (vote, then send to your wallet more NFTs, then vote again) ([tx-vote1](https://sepolia.etherscan.io/tx/0x34232eb16b281c0c997f6a4485921f99d8c9cf8030f5a6ed30120dd220438212),[tx-transfer](https://sepolia.etherscan.io/tx/0x5cfaf1d767445b72fc00601a0f66a32f8c26d7fe4cc6c56a5c4dc19186b95675),[tx-vote2](https://sepolia.etherscan.io/tx/0x136ae2f9f0c8412d094289a55ea4a7de395807d90c425ae67d382fbc1ec5c2c0),[dash](https://deploy-preview-1677.app.dev.decentdao.org/proposals/0?dao=sep:0x60d6a73397f4390aF5253cB4E39cA6b44fE9e29a))
  - [x] Multisig ([proposal](https://deploy-preview-1677.app.dev.decentdao.org/proposals/0xbbdda6ceb5da3627011123469ef1d07aa3a5b5066755fff3375e4e6459efca67?dao=sep:0x4db2a8619a0643B2F280D8DBf96097319A42ba5a))
  - [x] Snapshot ([snapshot space](https://testnet.snapshot.org/#/ethdomainlfg.eth/proposal/0x58000b75992ad0a3e0a3cb42744dcf90fb1d90dadb789ecdef105cff956d6687), [dash](https://deploy-preview-1677.app.dev.decentdao.org/proposals?dao=sep:0xa042F2b97855f72c4714B9E5ff9d603D2EE7F078))
- [x] Create child Safe ✅
  - [x] From Azorius ✅
    - [x] From Tokens ([dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x40fdB1FbcBCBA7F9dAaCF9C7386Ef57A0b0aE119))
      - [x] To Multisig ([tx](https://sepolia.etherscan.io/tx/0xeb6b984a1971b1f84b64f235c3205e1ad752e450769294bd9fba924cdfe0a33d))
      - [x] To Azorius Tokens ([tx](https://sepolia.etherscan.io/tx/0x0cbf6733ff7e9972e623b0a164ee0572103bf1149b03197717a5c7693389b476))
      - [x] To Azorius NFTs ([tx](https://sepolia.etherscan.io/tx/0xec7121067a0f6fb9e3538d6568e809b6fa6e256dffa31e64c76a69c0be261a4c))
    - [x] From NFTs ✅ ([dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x64f9Bf4643Ec12eeAF7c8Af4C9b7354E94Cb22c1))
      - [x] To Multisig ([tx](https://sepolia.etherscan.io/tx/0x3edebd685154e6e6bae98b91eef0d2bd3e87ea01f23651fc6c884acfe316eb10))
      - [x] To Azorius Tokens ([tx](https://sepolia.etherscan.io/tx/0x5dc122f849243c237ec862bb7c6affc6000288df46a0f1675efe17110f1d1ff1))
      - [x] To Azorius NFTs ([tx](https://sepolia.etherscan.io/tx/0x4d9f4d0f11794639a9cdd7e98073119f0000d4e133601e1b868f9255bb8d7637))
  - [x] From Multisig ✅ ([dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x4db2a8619a0643B2F280D8DBf96097319A42ba5a))
    - [x] To Multisig ([tx](https://sepolia.etherscan.io/tx/0xd1d71e44c8bdd0b3a49b7bd88d388bbde3fea3ae4cdfcb37c112319a75b0d7a1))
    - [x] To Azorius Tokens ([tx](https://sepolia.etherscan.io/tx/0x7e22da987d79a49331f782062c09769f7f657d8098d0e33745345925ab1cd41c))
    - [x] To Azorius NFTs ([tx](https://sepolia.etherscan.io/tx/0x1c762a0f2233bc571290f80254baeef345f3034e0197c78c3cf7f0babb53cc0d))
- [x] Initiate a Freeze  ✅ (unchecked boxes below were previously blocked because menu option hadn't been showing, but successful clawback tests thereafter on safes starting from scratch show that freezes in those contexts do pass, when the menu option does show)
  - [x] on Multisig Child from Azorius Tokens parent ([tx](https://sepolia.etherscan.io/tx/0x49e2842f9eee027f08afc0749c5724656a594e8059b24e23c25959e3ac347989),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0xc4406a86437b8f6750bed3306a4cfde95b0e3f6c))
  - [ ] on Multisig Child from Azorius NFTs parent ()
  - [x] on Multisig Child from Multisig parent ([tx](https://sepolia.etherscan.io/tx/0x0eae76f7118aca0e0f9f708a9f1544f60956313fa4ac320b2f88f7e28cf1d557),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0xfcfb5362dd82959d01b67b1bfb0d4ec79724cd2b))
  - [x] on Azorius Tokens Child from Azorius Tokens parent ([tx](https://sepolia.etherscan.io/tx/0x2fd3ae0b7b1f1aadbf711d9af480fcd2762c14446ab58c66756ee303a0d81abf),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x4842f65702781b26befd1d0da1ce6ca87f84c60a))
  - [ ] on Azorius Tokens Child from Azorius NFTs parent ()
  - [x] on Azorius Tokens Child from Multisig parent ([tx](https://sepolia.etherscan.io/tx/0xcb1dd4b56fdb5e52786d107218103bd88c0f70ba8c2fb22e5bb898b12098acb5),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0xee6423b7e1e2b897b9a3d1b2495323d21c21eb8e))
  - [ ] on Azorius NFTs Child from Azorius Tokens parent () 
  - [ ] on Azorius NFTs Child from Azorius NFTs parent ()
  - [x] on Azorius NFTs Child from Multisig parent ([tx](https://sepolia.etherscan.io/tx/0x0f7c685b9019c466d1f263f6791257d1023fc6d130523a1fba1714bca020c13a),[dash](https://deploy-preview-1677.app.dev.decentdao.org/))
- [x] Create Clawback proposal on Frozen DAO ✅
  - [x] on Multisig Child from Azorius Tokens parent ([tx](https://sepolia.etherscan.io/tx/0x8f27f38592c29fa850dae99d02f41c9ce6482b3a4dc100063e8fdcd3e8f5890e),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0xa042F2b97855f72c4714B9E5ff9d603D2EE7F078))
  - [x] on Multisig Child from Azorius NFTs parent ([tx](https://sepolia.etherscan.io/tx/0xddee30c1101178c26e42c2653c1edb821bd405951eaa795274b03a9810108b1b),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x8E5085Cbb3EccB13fc5EAb26B81e44b4e3105911))
  - [x] on Multisig Child from Multisig parent ([tx](https://sepolia.etherscan.io/tx/0xf2131b3aee2c37a3e4f5955c34f348d98d7f9fb04144f9c08767ec281ce0237d),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x93B4D1aF2028E40545EB7FBb21f889334B9203b0))
  - [x] on Azorius Tokens Child from Azorius Tokens parent ([tx](https://sepolia.etherscan.io/tx/0xeae469af8f88f2a68da9747aafcb780934df9b22ac6f26d4a4ac884ff6389ec4),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0xa042F2b97855f72c4714B9E5ff9d603D2EE7F078))
  - [x] on Azorius Tokens Child from Azorius NFTs parent ([tx](https://sepolia.etherscan.io/tx/0x6a48b31177c2637a974790afafd3e3ffbc017f6e9c87d02a20e26811e27edb7c),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x8E5085Cbb3EccB13fc5EAb26B81e44b4e3105911))
  - [x] on Azorius Tokens Child from Multisig parent ([tx](https://sepolia.etherscan.io/tx/0xfd58b47078c67264e6a184224d21d83b4c93d5edb1205932966861132dc92620),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x93B4D1aF2028E40545EB7FBb21f889334B9203b0))
  - [x] on Azorius NFTs Child from Azorius Tokens parent ([tx](https://sepolia.etherscan.io/tx/0x25a0b13deca470ece769ce638cb40bf5e08985ec81ac275c58a6f9a0d8df0932),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0xa042F2b97855f72c4714B9E5ff9d603D2EE7F078))
  - [x] on Azorius NFTs Child from Azorius NFTs parent ([tx](https://sepolia.etherscan.io/tx/0x19e5a0842f764b9941b953b2fe682494e632c14c8c9e2ef782b468bd1abea7d6),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x8E5085Cbb3EccB13fc5EAb26B81e44b4e3105911))
  - [x] on Azorius NFTs Child from Multisig parent ([tx](https://sepolia.etherscan.io/tx/0x9f7665a5164deb1423e9573044103c255306ca9d5d666efca90d94f5b06deb9e),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x93B4D1aF2028E40545EB7FBb21f889334B9203b0))
- [x] Create proposal template ✅
  - [x] Create first proposal template ✅
    - [x] Multisig ([tx](https://sepolia.etherscan.io/tx/0xbff71e86b433c50a8db9d82bf18924e1215800ea32af25097ac4737d91482405),[proposal](https://deploy-preview-1677.app.dev.decentdao.org/proposals/0x83f51004549107e4213e10925175c476fcebc233d6b458ca01206c1b43118a0c?dao=sep:0x1483224f28873794579cE3c767E740DD39723669))
    - [x] Azorius ERC-20 ([tx](https://sepolia.etherscan.io/tx/0x2f109d5b6d7ea2a9e351788357ffcaa5f168db5b8f7bf59b0effdfe84e77ef0c),[proposal](https://deploy-preview-1677.app.dev.decentdao.org/proposals/0?dao=sep:0xC4A01feF8886C2fF2eC8d7e697e8BaEcf253F2B0))
    - [x] Azorius ERC-721 ([tx](https://sepolia.etherscan.io/tx/0x36c5297d11927be6f823777ca90d1b2b4a8db098e2fdbb0b38bba3df8969686f),[proposal](https://deploy-preview-1677.app.dev.decentdao.org/proposals/3?dao=sep:0x187721341317Fc6f8Def65Ff0351224D298D5F4F))
  - [x] Create second proposal template ✅
    - [x] Multisig ([tx](https://sepolia.etherscan.io/tx/0xf489433ceb1a7890e69ac4f44e2a805c43ec286df79250ab7a18f02cffbff8ea),[proposal](https://deploy-preview-1677.app.dev.decentdao.org/proposals/0x19a04d606bf6e5eef1345e2b49f5dd9c3c9146c01c0f4be0778075bced121382?dao=sep:0x1483224f28873794579cE3c767E740DD39723669))
    - [x] Azorius ERC-20 ([tx](https://sepolia.etherscan.io/tx/0x14bd51edd28347d9c714a2ab2988b6d1fd65c07ff0ca7b335e2c1275d486b46c),[proposal](https://deploy-preview-1677.app.dev.decentdao.org/proposals/1?dao=sep:0xC4A01feF8886C2fF2eC8d7e697e8BaEcf253F2B0))
    - [x] Azorius ERC-721 ([tx](https://sepolia.etherscan.io/tx/0x2b92356007f992217b850258b3637ec9eb05b6a9703c30134582bae4a37835ea),[proposal](https://deploy-preview-1677.app.dev.decentdao.org/proposals/4?dao=sep:0x187721341317Fc6f8Def65Ff0351224D298D5F4F))
  - [x] Fork proposal template ✅
    - [x] Multisig
    - [x] Azorius ERC-20 ([dash](https://deploy-preview-1677.app.dev.decentdao.org/proposal-templates?dao=sep:0xC4A01feF8886C2fF2eC8d7e697e8BaEcf253F2B0))
    - [x] Azorius ERC-721 ([dash](https://deploy-preview-1677.app.dev.decentdao.org/proposal-templates?dao=sep:0x187721341317Fc6f8Def65Ff0351224D298D5F4F))
  - [x] Delete proposal template ✅
    - [x] Multisig ([tx](https://sepolia.etherscan.io/tx/0x203bbfff14203f18acc07b1e5371bc5f90556c7fda51b48e833e39116cafe249),[proposal](https://deploy-preview-1677.app.dev.decentdao.org/proposals/0xc05148b854a45588fd08ed35fc566e906616170991024f63c7d80afa10d31378?dao=sep:0x1483224f28873794579cE3c767E740DD39723669))
    - [x] Azorius ERC-20 ([tx](https://sepolia.etherscan.io/tx/0x84004bbaee81fa5ea1f4aa6248e70f10c0714c664af6c9fb6b4f4561a1c3e3a9),[dash](https://deploy-preview-1677.app.dev.decentdao.org/proposals/3?dao=sep:0xC4A01feF8886C2fF2eC8d7e697e8BaEcf253F2B0))
    - [x] Azorius ERC-721 ([tx](https://sepolia.etherscan.io/tx/0x65c28879dd635caf13df57e69d601b188b39355302a17de03d38863c8f6ab424),[dash](https://deploy-preview-1677.app.dev.decentdao.org/proposals/6?dao=sep:0x187721341317Fc6f8Def65Ff0351224D298D5F4F))
- [x] Create proposal from template ✅
  - [x] On Multisig ([tx](https://sepolia.etherscan.io/tx/0x086a3a20f19fe64f5faa37a30cd0166568b6c4ffdbcbd1361a85d3374ed57320),[proposal](https://deploy-preview-1677.app.dev.decentdao.org/proposals/0xe5a3e5cd9f111d98e1d86759001628268339ea38411f919a1f54438c0cf97511?dao=sep:0x1483224f28873794579cE3c767E740DD39723669))
  - [x] On Azorius ERC-20 ([tx](https://sepolia.etherscan.io/tx/0x070311c370362bacd76cd6884b41fd1087270ee2928a6270ff30420bae6941db),[dash](https://deploy-preview-1677.app.dev.decentdao.org/proposals/4?dao=sep:0xC4A01feF8886C2fF2eC8d7e697e8BaEcf253F2B0))
  - [x] On Azorius ERC-721 ([tx](https://sepolia.etherscan.io/tx/0x65c28879dd635caf13df57e69d601b188b39355302a17de03d38863c8f6ab424),[dash](https://deploy-preview-1677.app.dev.decentdao.org/proposals/6?dao=sep:0x187721341317Fc6f8Def65Ff0351224D298D5F4F))
- [x] Create proposal from all ways to do so in DAO Settings page ✅
  - [x] Multisig ✅
    - [x] Add signer ([tx](https://sepolia.etherscan.io/tx/0x7ca5219cff9d6bd1dbf033eabd83bb15e970dda9ef8fe6030acbbb89f971f1f4),[dash](https://deploy-preview-1677.app.dev.decentdao.org/home?dao=sep:0x4db2a8619a0643B2F280D8DBf96097319A42ba5a))
    - [x] Remove signer ([tx](https://sepolia.etherscan.io/tx/0x14aa9d4a2870945d3f780b1e2887f7eef6363a0f5349d7913bf2f14735166a28),[proposal](https://deploy-preview-1677.app.dev.decentdao.org/proposals/0x3721d9fdc7c57f6b333c7acc6798f88ebf3895fec52a453e74c461876e3c8546?dao=sep:0x4db2a8619a0643B2F280D8DBf96097319A42ba5a))
    - [x] Update safe name ([tx](https://sepolia.etherscan.io/tx/0xabf8481bed86f4c9ee997733f16fb158dfd5eac2b0cd5bdd95cefa51c93f2c2b),[proposal](https://deploy-preview-1677.app.dev.decentdao.org/proposals/0xfb510b92ccc27526a43be1e256c217ea0d3f8556e18246064e79427329dc9ef0?dao=sep:0x4db2a8619a0643B2F280D8DBf96097319A42ba5a))
  - [x] Update safe name ✅
    - [x] Azorius Tokens 
    - [x] Azorius NFTs
  - [x] Update snapshot space ✅
    - [x] Azorius Tokens 
    - [x] Azorius NFTs
    - [x] Multisig

### Observed Issues
- Treasury page is bugged -- showing inaccurate transfers (after clicking around, probably from the parent safe's treasury) (tracked in #2367):
Screenshot 2024-09-17 at 13 48 19

- Funky stuff's happening on 2nd time initiate freeze on separate subsafe
- Subsafe's freeze status does not reliably show. Sometimes countdown is missing
- Multisig proposal transaction hash before execute is misleading
~- freeze votes threshold still allows input more than parent safe signer threshold~ fixed
- Another intermittent error when loading up the proposals page (but inconsistent as a refresh "solves" it):
Screenshot 2024-09-04 at 15 35 51

- "Go Home" button doesn't work from Error boundary page =/
- Nft safes with multiple nfts might have weird behaviour on (create child safe) proposal details page
- Still think we need a louder, probably more persistent, call to Delegate voting tokens, as a lot of functionality is blocked until delegation happens, and it's not always clear why

### CODE REVIEW

**Comment by adamgall** [comment]
My only goal with this PR, now, is to get it merged cleanly, building, and running.

_viem's batching can be turned off_, let's worry about those strange issues we're seeing in a future PR.

main goal right now is to _get this merged_.

**Comment by adamgall** [comment]
@decentdao/engineering 

My only goal with this PR, now, is to get it merged cleanly, building, and running.

_viem's batching can be turned off_, let's worry about those strange issues we're seeing in a future PR.

main goal right now is to _get this merged_.

**Comment by Da-Colon** [comment]
I'm working on these conflicts

**Review by mudrila — APPROVED** [review]
Assuming there's no upcoming prod releases - I think we should be good to merge it now. If there will be something urgently needed for `main` - we can go through `hot-fix` branch targetting `main` branch
@adamgall @DarksightKellar @Da-Colon WDYT?

**Comment by adamgall** [comment]
> Assuming there's no upcoming prod releases - I think we should be good to merge it now. If there will be something urgently needed for `main` - we can go through `hot-fix` branch targetting `main` branch @adamgall @DarksightKellar @Da-Colon WDYT?

You know what, yes let's do it

**Comment by Da-Colon** [comment]
Let's do it

**Review by Da-Colon — APPROVED** [review]

**Comment by adamgall** [comment]
<iframe src="https://giphy.com/embed/3oKIPf3C7HqqYBVcCk" width="480" height="269" style="" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/reactionseditor-3oKIPf3C7HqqYBVcCk">via GIPHY</a></p>

**Pull request merged**
