### PR TITLE
Vote results tables / grids on mobile

### LINKED ISSUE #1903: Mobile signers and results tables
This issue is in response to https://github.com/decentdao/decent-interface/issues/1884

Please update mobile tables to scroll horizontally in lieu of condensing the data to fit. 
(Votes example shown, same pattern applies to signers)

[In Figma](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?m=auto&node-id=64%3A3591&t=cmhPW3aWoEd2sPrM-1)

Image

### PR DESCRIPTION
**Pull request by adamgall**
Fixes #1903 

On all Proposal types:

- Azorius
  - ERC20
  - ERC721
- Multisig
- Snapshot

Make the table that displays the voter results look much better on mobile (and desktop too tbh) by:

- keeping each row on one line (no line breaks)
- keeping all columns aligned
- allowing horizontal scrolls

### CODE REVIEW

**Review by xraystyle1980 — CHANGES_REQUESTED** [review]
Please increase `column-gap` to `chakra-space-5`

CleanShot - Arc - 2024-05-28 4@2x

**Comment by xraystyle1980** [comment]
Please move message down so that it doesn't sit flush at the top of page

screenshot

In Figma:
https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?m=auto&node-id=2705-4580&t=WDAyt4bKD13G4sVx-1
<details><summary>Browser metadata</summary>





```
Path:      /proposals/0?dao=sep:0x97Af37385945E150Bdc030f2dBe6AE1dfDe077AA
Browser:   Chrome 125.0.0.0 on Mac OS 10.15.7
Viewport:  1708 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1936.app.dev.decentdao.org%2Fproposals%2F0%3Fdao%3Dsep%3A0x97Af37385945E150Bdc030f2dBe6AE1dfDe077AA&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=125.0&resolution=1708x1027&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1936.app.dev.decentdao.org/proposals/0?dao=sep:0x97Af37385945E150Bdc030f2dBe6AE1dfDe077AA) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6656379ecd7ae70008772983&commentID=66565d0da1e5c6a7b66713e3&resolution=resolved)

**Comment by adamgall** [comment]
@tomstuart123 I pushed a fix to the "Loading Error" problem @xraystyle1980 pointed out (in this PR), before seeing your previous message. I think it's fine enough to sneak that fix in here, it's just a one line change.

**Review by tomstuart123 — APPROVED** [review]
makes sense @adamgall .

Reviewed and looks good from my side too

**Pull request merged**
