### PR TITLE
`[PRD]` Dashboard updates

### LINKED ISSUE #2522: Safe dashboard copy updates
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#1422ee9c5bc280ccb511c99154fc89f9

### PR DESCRIPTION
**Pull request by DarksightKellar**
Closes #2522

### CODE REVIEW

**Review by adamgall — DISMISSED** [review]
This PR doesn't cover all of the items in the linked issue

**Review by Da-Colon — APPROVED** [review]
runners failed for one reason or another but LGTM

**Review by mudrila — APPROVED** [review]

**Comment by Da-Colon** [comment]
Netlify and these runners don't like this PR....

**Comment by parkermccurley** [comment]
Assuming @adamgall's requested changes were completed, approved

**Pull request merged**
