### PR TITLE
Revert safe reset refactor

### PR DESCRIPTION
**Pull request by DarksightKellar**
In a previous commit, we moved the calls to `resetSafeState` and `resetHatsStore` from the home page to the dao controller component, as that felt like the more logical place to put it. 

While the argument is still valid, this just led to more bugs due to the brittle nature of the flow of safe state changes.

We have tried moving the `reset`s higher up the hierarchy into `Layout/index.tsx` with slightly better result, but far from good enough. 

That said, the decision was made to revert this move for now. This fixes the original bug described in #2084, with the caveat that there are edge cases around switching safes instantly using the search bar, when already on the roles page of the current safe.

This will have to do for now as the most common UX flows to end up on different safes should be fine. I do plan to continue to dig into the original safe state issues in the meantime until more pressing issues get on the radar.

### CODE REVIEW

**Comment by DarksightKellar** [comment]
@tomstuart123 Could you checkout the description on this PR please and test to confirm the fix on your end?

**Review by tomstuart123 — APPROVED** [review]

**Comment by tomstuart123** [comment]
@DarksightKellar thanks man, very clear description 

I just jumped between Safe's via the homepage-->DAOhome-->DAO roles--> homepage --> etc. This worked 100% of the time on 6 tries.

I was able - as you mentioned to replicate the edge case you mentioned with the search bar. However, I can confirm that this is fine. To replicate it you need to move super fast in the UI (i.e. power users) and even then it does reload automatically eventually

Approved

**Comment by tomstuart123** [comment]
Question @DarksightKellar / @decentdao/engineering - 

will this reverted change of 'call' location have any other user impact? Or was it just a general 'code efficiency' / 'logical place' reason ?

**Comment by DarksightKellar** [comment]
> Question @DarksightKellar / @decentdao/engineering -
> 
> will this reverted change of 'call' location have any other user impact? Or was it just a general 'code efficiency' / 'logical place' reason ?

@tomstuart123 Yeah this revert just sent back logic to the way it was already on develop. Plus the "fix" on top of that. The move (that ended up not working out) was meant to patch up edge case resetting logic flaws that do exist right now regardless and were discovered while fixing the original issue.

For example, having the reset logic exist in the homepage means that going to the homepage is the only to _reliably_ reset safe state. If the "homepage" changes at some point in the future, that affects this guarantee.

**Pull request merged**
