### PR TITLE
Fix address input field validation

### LINKED ISSUE #2355: Send Assets recipient input is kind of flakey when using ENS name
https://github.com/user-attachments/assets/457e44c1-b883-401c-b471-2f995033041d

### PR DESCRIPTION
**Pull request by adamgall**
fixes #2355 

The only sucky thing here is that it requires the user to click out of the address input field in order for the validation to work. Spoke with @Da-Colon about potential alternative approaches to "fix" this, but I don't want to put more time into it.

To test (and compare behavior between dev/prod and this PR)
1. load up a DAO which has some treasury assets, and you're able to create proposals on
2. go to the Treasury page
3. click the "send assets" button or whatever it's called
4. Play around with typing valid and invalid ENS names into the recipient field.

The behavior should be more "consistent" on this branch. Behavior meaning, input validation and the "create proposal" button becoming enabled.

### CODE REVIEW

**Review by Da-Colon — APPROVED** [review]

**Comment by adamgall** [comment]
there are still some issues with this code... Here's what I'm experiencing:

1. go to Treasury
2. open Send Assets modal
3. select asset and type valid amount
4. type valid ENS name
5. debouncing works as expected, and the address is properly validated, and the "Submit Proposal" button becomes active!! yay!
6. BUT, then, it takes TWO clicks on the Submit Proposal button until that action is registered. Clicking it once, as far as I can tell, will make the form re-validate one more time, but it doesn't actually trigger the action to happen. Gotta click it one more time after that. Kinda weird.

**Comment by Da-Colon** [comment]
> there are still some issues with this code... Here's what I'm experiencing:
> 
> 1. go to Treasury
> 2. open Send Assets modal
> 3. select asset and type valid amount
> 4. type valid ENS name
> 5. debouncing works as expected, and the address is properly validated, and the "Submit Proposal" button becomes active!! yay!
> 6. BUT, then, it takes TWO clicks on the Submit Proposal button until that action is registered. Clicking it once, as far as I can tell, will make the form re-validate one more time, but it doesn't actually trigger the action to happen. Gotta click it one more time after that. Kinda weird.

that is weird. I'll look into it

**Comment by Da-Colon** [comment]
> there are still some issues with this code... Here's what I'm experiencing:
> 
> 1. go to Treasury
> 2. open Send Assets modal
> 3. select asset and type valid amount
> 4. type valid ENS name
> 5. debouncing works as expected, and the address is properly validated, and the "Submit Proposal" button becomes active!! yay!
> 6. BUT, then, it takes TWO clicks on the Submit Proposal button until that action is registered. Clicking it once, as far as I can tell, will make the form re-validate one more time, but it doesn't actually trigger the action to happen. Gotta click it one more time after that. Kinda weird.

Just attempted a few times not getting htat behavior

**Comment by adamgall** [comment]
> > there are still some issues with this code... Here's what I'm experiencing:
> > 
> > 1. go to Treasury
> > 2. open Send Assets modal
> > 3. select asset and type valid amount
> > 4. type valid ENS name
> > 5. debouncing works as expected, and the address is properly validated, and the "Submit Proposal" button becomes active!! yay!
> > 6. BUT, then, it takes TWO clicks on the Submit Proposal button until that action is registered. Clicking it once, as far as I can tell, will make the form re-validate one more time, but it doesn't actually trigger the action to happen. Gotta click it one more time after that. Kinda weird.
> 
> Just attempted a few times not getting htat behavior

Hmmmmm really? I'm consistently reproducing it on my side. Screenshare?

**Comment by adamgall** [comment]
Seems like a Frame issue, not gonna worry about it.

**Pull request merged**
